### ISSUE TITLE
请问此 RESTKit 有计划开源吗？

### ISSUE THREAD

**Issue by dong4j** [newhoo/RESTKit-Doc#2]
你好，计划写一款功能相似的插件，因为我们的基础框架是在 SpringMVC 的基础上再次封装了一层，只会提供 GET/POST/DELETE 等通用接口出来，然后再根据 header 中的参数转发到下层的具体 service，这样对开发调试都不是很方便，因此想开发与 RESTKit 类似的查看，不知道能不能开源学习一下。

**Comment by huzunrong** [comment]
暂时没有开源计划。RESTKit已经提供了扩展点，可以提供自己的扩展来增加其他方式的API扫描，可以参考https://github.com/huzunrong/RESTKit-Doc#plugin-extension

**Comment by newhoo** [comment]
想想还是开源了，参考 https://github.com/newhoo/RESTKit

**Comment by dong4j** [comment]
感谢大佬
